name: Compile and publish release

on:
  release:
    types: [created]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout code
        uses: actions/checkout@v3

      - name: Setup | Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Build | Tests
        env:
          DATABASE_SECRET: ${{ secrets.DATABASE_SECRET}}
          DATABASE_URL: ${{ secrets.DATABASE_URL}}
        run: cargo test  

      - name: Compile and publish
        uses: rust-build/rust-build.action@v1.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: x86_64-pc-windows-gnu 
