name: Test and release

on:
  push:
  workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout code
        uses: actions/checkout@v2

      - name: Setup | Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: x86_64-unknown-linux-musl

      - id: cargo-cache
        name: Cache
        uses: Swatinem/rust-cache@v1
        with:
          key: test

      - name: Build | Tests
        working-directory: ./sensor
        env:
          DATABASE_SECRET: ${{ secrets.DATABASE_SECRET}}
          DATABASE_URL: ${{ secrets.DATABASE_URL}}
        run: cargo test  

  release:
    needs: test
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-musl]
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          SRC_DIR: ./sensor  
