name: Test and deploy health check

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Test and deploy health check
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout code
        uses: actions/checkout@v3

      - name: Build | Test
        env:
            DATABASE_SECRET: ${{ secrets.DATABASE_SECRET}}
            DATABASE_URL: ${{ secrets.DATABASE_URL}}
        run: cargo test --release       
