name: Test and deploy health check

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Test and deploy health check
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout code
        uses: actions/checkout@v3

      - name: Setup | Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Setup | Npm install
        run: npm ci
        working-directory: ./views

      - name: Build | Build front-end
        run: npm run build
        working-directory: ./views

      - name: Setup | Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build | Test
        env:
            DATABASE_SECRET: ${{ secrets.DATABASE_SECRET}}
            DATABASE_URL: ${{ secrets.DATABASE_URL}}
        run: cargo test --release       

      - name: Build and publish "latest" Docker image
        uses: VaultVulp/gp-docker-action@1.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} 
          image-name: ${{ github.event.repository.name }} 
          dockerfile: Containerfile
